# Generated by Django 3.0.8 on 2020-07-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('content', models.TextField()),
            ],
        ),
    ]
